config/routes.rb
#Edited By: Charles Kluznik
#Added routes for new_member and submit_member
#Date: 12/04/2022
Rails.application.routes.draw do
  resources :evaluations
  root 'home#index'  
  resources :home
  resources :teams
  resources :courses
  resources :admins
  resources :students
  resources :project_evaluations
  resources :tech_task_evaluations
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get 'teams/:id/new_member' => 'teams#new_member', :as => 'new_member' #get route for new_member page
  post 'teams/:id/submit_member' => 'teams#submit_member', :as => 'submit_member' #post route for submitting new_member form
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
</div>

app/views/admins/_form.html.erb
<!-- Owner: David Paquin !-->
<!-- Date: 11/29/2022 !-->
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  First name: <%= form.text_field :first_name %><br>
  Last name: <%= form.text_field :last_name %><br>
  OSU name.#: <%= form.text_field :namedotnumber %><br>
  <%= form.submit "Save"%>
  </div>
<% end %>

app/views/admins/edit.html.erb
<!-- Owner: David Paquin !-->
<!-- Date: 11/29/2022 !-->

<%= stylesheet_link_tag 'profile', media: "all" %>
<h1>Edit Profile Information</h1>

<%= render "form", admin: @admin %>

<br>

<div>
</div>

app/views/admins/index.html.erb
<!-- Owner: David Paquin !-->
<!-- Date: 11/29/2022 !-->
<p style="color: green"><%= notice %></p>

<h1>Admins</h1>

<div id="admins">
  <% @admins.each do |admin| %>
    <p>
      <%= link_to admin[:first_name].to_s+" "+admin[:last_name].to_s, admin %>
    </p>
  <% end %>
</div>

<%= link_to "New admin", new_admin_path %>

app/views/admins/new.html.erb
<!-- Owner: David Paquin !-->
<!-- Date: 11/29/2022 !-->
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<!-- Owner: David Paquin !-->
<!-- Date: 11/29/2022 !-->

<%= stylesheet_link_tag 'profile', media: "all" %>
<p style="color: green"><%= notice %></p>

<%= render @admin %>
  First name: <%= @admin[:first_name] %><br>
  Last name: <%= @admin[:last_name] %><br>
  OSU name.#: <%= @admin[:namedotnumber] %><br>
  <br>
<div>
  <%= link_to "Edit profile information", edit_admin_path(@admin) %><br> 
  <%= button_to "Delete Account", @admin, method: :delete %>
</div>