config/routes.rb
#Edited By: Charles Kluznik
#Added routes for new_member and submit_member
#Date: 12/04/2022
Rails.application.routes.draw do
  resources :evaluations
  root 'home#index'  
  resources :home
  resources :teams
  resources :courses
  resources :admins
  resources :students
  resources :project_evaluations
  resources :tech_task_evaluations
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get 'teams/:id/new_member' => 'teams#new_member', :as => 'new_member' #get route for new_member page
  post 'teams/:id/submit_member' => 'teams#submit_member', :as => 'submit_member' #post route for submitting new_member form
end

app/views/partials/_footer.html.erb
<%# Created By: David Paquin %>
<%# Creation Date: 11/20/22 %>

<%= stylesheet_link_tag '_footer', media: "all" %>

<footer>
  <div id="foo">
    Dr. Naeem Shareef
  </div>
  <div id="backToTop">
    <a href="#">
      Back To Top
    </a>
  </div>
  <span id="info">
    CSE 3901 AU22 - Runtime Terrors — The Ohio State University
  </span>
</footer>

app/views/partials/_navbar.html.erb
<%# Created By: David Paquin %>
<%# Creation Date: 11/20/22 %>
<%# Edit By: Alex Echanove %>
<%# Date: 11/29/22 %>
<%# Edit By: Ross Imbrock %>
<%# Date: 12/04/22 %>
<%# Edit By: Ross Imbrock %>
<%# Date: 12/07/22 %>

<%= stylesheet_link_tag '_navbar', media: "all" %>

<nav class="navbar navbar-expand">
  <a class="navbar-brand" href="/">P.E. 3000</a>
    <ul class="navbar-nav">
    <% if user_signed_in? %>
        <li class = "nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path , data: {turbo_method: :delete}, class: 'nav-link' %>
        </li>

        <% if current_user.admin?%>
            <li class = "nav-item">
              <%= link_to 'Profile', "/admins/#{(Admin.find_by namedotnumber: current_user.namedotnumber).id}" , class: 'nav-link'%>
            </li>
            <li class = "nav-item">
			    <%= link_to "Courses", courses_path , class: 'nav-link'%>
            </li>
            <li class = "nav-item">
			    <%= link_to "Teams", teams_path , class: 'nav-link'%>
            </li>
            <li class = "nav-item">
			    <%= link_to "Evaluations", evaluations_path , class: 'nav-link'%>
            </li>
        <% else %>
            <li class = "nav-item">
              <%= link_to 'Profile', "/students/#{(Student.find_by namedotnumber: current_user.namedotnumber).id}" , class: 'nav-link'%>
            </li>
            <li class = "nav-item">
                <%= link_to 'Project Evaluation', project_evaluations_url , class: 'nav-link'%>
            </li>
            <li class = "nav-item">
                <%= link_to 'Tech Task Evaluation', tech_task_evaluations_url , class: 'nav-link'%>
            </li>
        <% end %>

    <% else %>
        <li class = "nav-item">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link'%>
        </li>
        <li class = "nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link'%>
        </li>
    <% end %>
    </ul>
</nav>