config/routes.rb
#Edited By: Charles Kluznik
#Added routes for new_member and submit_member
#Date: 12/04/2022
Rails.application.routes.draw do
  resources :evaluations
  root 'home#index'  
  resources :home
  resources :teams
  resources :courses
  resources :admins
  resources :students
  resources :project_evaluations
  resources :tech_task_evaluations
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get 'teams/:id/new_member' => 'teams#new_member', :as => 'new_member' #get route for new_member page
  post 'teams/:id/submit_member' => 'teams#submit_member', :as => 'submit_member' #post route for submitting new_member form
end

app/models/tech_task_evaluation.rb
class TechTaskEvaluation < ApplicationRecord
end

app/controllers/tech_task_evaluations_controller.rb
#Created By: Ross Imbrock
#Creation Date: 12/03/22 
class TechTaskEvaluationsController < ApplicationController
  before_action :set_tech_task_evaluation, only: %i[ show edit update destroy ]

  # GET /tech_task_evaluations or /tech_task_evaluations.json
  def index
    @tech_task_evaluations = TechTaskEvaluation.all
  end

  # GET /tech_task_evaluations/1 or /tech_task_evaluations/1.json
  def show
  end

  # GET /tech_task_evaluations/new
  def new
    @tech_task_evaluation = TechTaskEvaluation.new
  end

  # GET /tech_task_evaluations/1/edit
  def edit
  end

  # POST /tech_task_evaluations or /tech_task_evaluations.json
  def create
    #Allowing all params for :teamid to work properly
    params.permit!
    @tech_task_evaluation = TechTaskEvaluation.new(tech_task_evaluation_params)

    respond_to do |format|
      if @tech_task_evaluation.save
        format.html { redirect_to tech_task_evaluation_url(@tech_task_evaluation), notice: "Tech task evaluation was successfully created." }
        format.json { render :show, status: :created, location: @tech_task_evaluation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tech_task_evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tech_task_evaluations/1 or /tech_task_evaluations/1.json
  def update
    respond_to do |format|
      if @tech_task_evaluation.update(tech_task_evaluation_params)
        format.html { redirect_to tech_task_evaluation_url(@tech_task_evaluation), notice: "Tech task evaluation was successfully updated." }
        format.json { render :show, status: :ok, location: @tech_task_evaluation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tech_task_evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tech_task_evaluations/1 or /tech_task_evaluations/1.json
  def destroy
    @tech_task_evaluation.destroy

    respond_to do |format|
      format.html { redirect_to tech_task_evaluations_url, notice: "Tech task evaluation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tech_task_evaluation
      @tech_task_evaluation = TechTaskEvaluation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tech_task_evaluation_params
      params.require(:tech_task_evaluation).permit(:overall, :research, :presentation, :best_qualities, :improve_on, :professor, :other, :teamid)
    end
end

app/helpers/tech_task_evaluations_helper.rb
module TechTaskEvaluationsHelper
end

app/views/tech_task_evaluations/_form.html.erb
<!--Author: Ross Imbrock-->
<!--Created on: 12/03/22-->
<%= form_with(model: tech_task_evaluation) do |form| %>
<p>
  Teams: <%= form.select :teamid , Student.find_by(namedotnumber: current_user.namedotnumber).teams.map {|team| team.id} %><br>
</p>
<!--Manager Question-->
  <div class = "form-group">
    <%= form.label "Select the option you believe reflects the effort and contributions of the Tech Task Overall Manager.", style: "display: block" %>
    <%= form.radio_button :overall, 'excellent', :checked => false%>
    <%= form.label :overall, "Excellent", :value => "true" %><br />
    <%= form.radio_button :overall, 'great', :checked => false%>
    <%= form.label :overall, "Great", :value => "true" %><br />
    <%= form.radio_button :overall, 'average', :checked => false%>
    <%= form.label :overall, "Average", :value => "true" %><br />
    <%= form.radio_button :overall, 'poor', :checked => false%>
    <%= form.label :overall, "Poor", :value => "true" %>
  </div>
<!--Team Questions-->
  <div class = "form-group">
    <%= form.label "Describe each team member's effort and contributions to the research in this project.", style: "display: block" %>
    <%= form.text_area :research, class: "form-control"  %>
  </div>

  <div class = "form-group">
    <%= form.label "Describe each team member's effort and performance during the presentation.", style: "display: block" %>
    <%= form.text_area :presentation, class: "form-control"  %>
  </div>

  <div class = "form-group">
    <%= form.label "Describe the best contributions each team member made to the project.", style: "display: block" %>
    <%= form.text_area :best_qualities, class: "form-control"  %>
  </div>

  <div class = "form-group">
    <%= form.label "Describe what each team member could improve on in the future.", style: "display: block" %>
    <%= form.text_area :improve_on, class: "form-control"  %>
  </div>

  <div class = "form-group">
    <%= form.label "Provide any comments you would like the professor or grader to know.", style: "display: block" %>
    <%= form.text_area :professor, class: "form-control"  %>
  </div>

  <div class = "form-group">
    <%= form.label "Provide any other remarks you would like make.", style: "display: block" %>
    <%= form.text_area :other, class: "form-control"  %>
  </div>

  <div>
    <%= form.submit "Submit" %>
  </div>
    <% if tech_task_evaluation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tech_task_evaluation.errors.count, "error") %> prohibited this tech_task_evaluation from being saved:</h2>

      <ul>
        <% tech_task_evaluation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/tech_task_evaluations/_tech_task_evaluation.html.erb
<!--Author: Ross Imbrock-->
<!--Created on: 12/03/22-->
<div id="<%= dom_id tech_task_evaluation %>">
  <p>
    <strong>Team ID:</strong>
    <%= tech_task_evaluation.teamid %>
  </p>

  <p>
    <strong>Overall Manager Rating:</strong>
    <%= tech_task_evaluation.overall %>
  </p>

  <p>
    <strong>Research Contributions:</strong>
    <%= tech_task_evaluation.research %>
  </p>

  <p>
    <strong>Presentation Ratings:</strong>
    <%= tech_task_evaluation.presentation %>
  </p>

  <p>
    <strong>Best qualities of teammates:</strong>
    <%= tech_task_evaluation.best_qualities %>
  </p>

  <p>
    <strong>Teammates need to improve on:</strong>
    <%= tech_task_evaluation.improve_on %>
  </p>

  <p>
    <strong>Notes to professor:</strong>
    <%= tech_task_evaluation.professor %>
  </p>

  <p>
    <strong>Other comments:</strong>
    <%= tech_task_evaluation.other %>
  </p>

</div>

app/views/tech_task_evaluations/edit.html.erb
<!--Author: Ross Imbrock-->
<!--Created on: 12/03/22-->
<h1>Editing Tech Task Team Evaluation</h1>

<%= render "form", tech_task_evaluation: @tech_task_evaluation %>

<br>

<div>
  <%= link_to "Show this tech task evaluation", @tech_task_evaluation %> |
  <%= link_to "Back to tech task evaluations", tech_task_evaluations_path %>
</div>

app/views/tech_task_evaluations/index.html.erb
<!--Author: Ross Imbrock-->
<!--Created on: 12/04/22-->
<head>
<%= stylesheet_link_tag 'evaluation', media: "all" %>
</head>
<p style="color: green"><%= notice %></p>

<h1>Tech Task Team Evaluation</h1>
<p class = "index">This peer evaluation must be completed individually by you and not with your team. All of your answers will be kept confidential.</p>
<%= button_to "Begin Team Evaluation", new_tech_task_evaluation_path, :class => "start", :method => "get" %>

app/views/tech_task_evaluations/new.html.erb
<!--Author: Ross Imbrock-->
<!--Created on: 12/04/22-->
<head>
<%= stylesheet_link_tag 'evaluation', media: "all" %>
</head>
<h1>Tech Task Peer Evaluation</h1>

<%= render "form", tech_task_evaluation: @tech_task_evaluation %>

app/views/tech_task_evaluations/show.html.erb
<!--Author: Ross Imbrock-->
<!--Created on: 12/04/22-->
<head>
<%= stylesheet_link_tag 'evaluation', media: "all" %>
</head>
<p style="color: green"><%= notice %></p>

<%= render @tech_task_evaluation %>

<div>
  <%= link_to "Edit Evaluation", edit_tech_task_evaluation_path(@tech_task_evaluation) %> |
  <%= link_to "Delete Evaluation", @tech_task_evaluation, data: {turbo_method: :delete, turbo_confirm: "Are you sure you would like to delete your evaluation?"} %>
</div>